Async calls implementation
Vonage/vonage-dotnet-sdk pull request #230
Opened 2020-10-06 11:04 UTC by smikis

Will solve https://github.com/Vonage/vonage-dotnet-sdk/issues/126

2020-10-07 12:53 UTC, slorello89 requested changes
Hi @smikis - Thanks for this PR - it's a major undertaking. The issue is, as this is currently constituted it would be a breaking change to the SDK as folks would have to switch to the async implementation when upgrading. If this was an additive rather than a breaking change it would be something I'd like to use.

2020-10-07 13:11 UTC, smikis commented
Any ideas how do you want to approach this? Just duplicating code for every method does not seem right to me

2020-10-07 13:35 UTC, smikis commented
I'll try to wrap non async calls in Task.Run
It should work out fine

2020-10-07 14:13 UTC, smikis commented
Update to include both methods. Async method is primary one, and non async method just calls async method and returns result.
Should I revert documentation and refer to non async methods?

2020-10-08 15:20 UTC, slorello89 requested changes
The way you implemented this I don't think we need to have the async methods called from the unit tests - should be sufficient for coverage to use the sync methods only so I'd ask that you revert the unit test updates (ignore code cov somewhat as it doesn't handle the branches created by the compiler for async that well)

2020-10-08 15:32 UTC, smikis commented on Vonage.Test.Unit/AccountTest.cs
> +        public async Task GetAccountBalance(bool passCreds)
Sure, make sense. Reverted test files

2020-10-15 13:05 UTC, slorello89 requested changes
Hi @smikis - I only see one more thing I'd ask you to change - other than that I'm going to do some manual tests on my end to validate everything still works outside of the unit tests - looking forward to having this in the SDK :)

2020-10-15 13:05 UTC, slorello89 commented on Vonage/Request/ApiRequest.cs
>              {
just below here it's reading out of the stream synchronously - that can be done using the Async/Await pattern as well

2020-10-16 09:40 UTC, smikis commented on Vonage/Request/ApiRequest.cs
>              {
Updated

2020-10-19 12:57 UTC, slorello89 approved these changes
@smikis - Thank you so much for this - a stellar contribution. Happy Hacktoberfest! 🎃🎃🎃

2020-10-19 12:57 UTC, merged