Issue 1221 Fix
Vonage/vonage-dotnet-sdk pull request #231
Opened 2020-10-06 16:48 UTC by gagandeepp

2020-10-07 12:31 UTC, slorello89 requested changes
A couple of changes need to be made to the IVoiceClient to match the proposed method signatures.

Also - the `VoiceClient` implements the `IVoiceClient` thus it needs to implement the new APIs

2020-10-07 12:31 UTC, slorello89 commented on Vonage/Voice/IVoiceClient.cs
> +        CallResponse CreateCall(PhoneEndpoint toNumber, PhoneEndpoint fromNumber , Ncco ncco);
`toNumber` and `fromNumber` in this instances should be strings - the client itself should build the call command from this.

2020-10-07 12:31 UTC, slorello89 commented on Vonage/Voice/IVoiceClient.cs
> +        CallResponse CreateCall(Endpoint toEndPoint, PhoneEndpoint fromNumber, Ncco ncco);
`fromNumber` should be a string in this case, the client will build the `PhoneEndpoint`

2020-10-08 07:00 UTC, gagandeepp commented on Vonage/Voice/IVoiceClient.cs
> +        CallResponse CreateCall(Endpoint toEndPoint, PhoneEndpoint fromNumber, Ncco ncco);
I will work on this weekend,sorry for late response

2020-10-11 09:41 UTC, gagandeepp commented on Vonage/Voice/IVoiceClient.cs
> +        CallResponse CreateCall(PhoneEndpoint toNumber, PhoneEndpoint fromNumber , Ncco ncco);
DONE

2020-10-11 09:41 UTC, gagandeepp commented on Vonage/Voice/IVoiceClient.cs
> +        CallResponse CreateCall(Endpoint toEndPoint, PhoneEndpoint fromNumber, Ncco ncco);
done

2020-10-13 11:00 UTC, gagandeepp commented
@slorello89  Please review the changes

2020-10-13 12:39 UTC, slorello89 requested changes
New APIs need to be implemented. Also needs tests to make sure everything is working.

2020-10-13 12:39 UTC, slorello89 commented on Vonage/Voice/VoiceClient.cs
> +            throw new NotImplementedException();
These two methods need to be implemented, can't just do exception throws. See https://developer.nexmo.com/voice/voice-api/code-snippets/make-an-outbound-call-with-ncco for inspiration.

2020-10-16 16:14 UTC, gagandeepp commented
@slorello89  Changes are made please review

2020-10-19 13:15 UTC, slorello89 requested changes
Hi @gagandeepp - just a couple of minor items I'd ask you to clean up before I merge this - otherwise this looks great!

2020-10-19 13:15 UTC, slorello89 commented on Vonage.Test.Unit/VoiceClientTests.cs
> +        public void CreateCallv2()
Would you mind changing the name of this test to something along the lines of "CreateCallWithEndpointAndNcco" - `v2` has a separate meaning regarding API versioning so it's a bit ambiguous in this context

2020-10-19 13:15 UTC, slorello89 commented on Vonage/Voice/VoiceClient.cs
> +             {
indentation is off.

2020-10-19 13:15 UTC, slorello89 commented on Vonage/Voice/VoiceClient.cs
> +              {
indentation is a bit off here.

2020-10-21 05:44 UTC, gagandeepp commented
@slorello89  Please review

2020-10-21 21:29 UTC, slorello89 requested changes
Hi @gagandeepp - pulled this in for final testing and noticed a couple of things I didn't spot when eyeballing it:

1: the VoiceClient should still be using `v1` of the voice API
2: the two APIs you added are async tasks which is fine, but in keeping with the pattern of the rest of the SDK there should be an async and sync version of the method, the sync method will just call the async and call the `GetAwaiter().GetResult()`
3: You're using some of the old Nexmo Data Structures (I think intellense prefers them alphabetically - hiding that namespace is on my todo list) - these will "work" - but were deprecated when we rebranded everything  -> Vonage and shouldn't be part of the new requests.
4: In the API where it requests a to the endpoint, that's meant to be generic - that way people can just pass whatever to endpoint they want (e.g. SIP/app/WebSocket) and not have to worry about initializing one.

2020-10-21 21:29 UTC, slorello89 commented on Vonage/Voice/IVoiceClient.cs
> +using Nexmo.Api.Voice.Nccos;
Wrong namespace - should be `Vonage.Voice.Nccos` (Nexmo ones are left in for legacy users)

2020-10-21 21:29 UTC, slorello89 commented on Vonage/Voice/VoiceClient.cs
> +using Nexmo.Api.Voice.Nccos;
Wrong Namespace

2020-10-21 21:29 UTC, slorello89 commented on Vonage/Voice/VoiceClient.cs
> +        public const string CALLS_ENDPOINT_LATEST = "v2/calls";
should not be using v2 yet

2020-10-21 21:29 UTC, slorello89 commented on Vonage/Voice/IVoiceClient.cs
> +        Task<CallResponse> CreateCall(string toNumber, string fromNumber, Nccos.Ncco ncco);
Just noticed these were async, there should be two methods defined for each of these APIs, one sync, one Async, the sync one will just call the async one with, and return the `GetAwaiter().GetResult()` from it.

2020-10-21 21:29 UTC, slorello89 commented on Vonage/Voice/IVoiceClient.cs
> +        Task<CallResponse> CreateCall(PhoneEndpoint toEndPoint, string fromNumber, Nccos.Ncco ncco);
keep the endpoint type generic - just have it be of type `Endpoint` - the purpose here is that it will enable folks to point to the different endpoints

2020-10-21 21:29 UTC, slorello89 commented on Vonage/Voice/VoiceClient.cs
> +
extra whitespace

2020-10-22 15:48 UTC, gagandeepp commented on Vonage/Voice/IVoiceClient.cs
> +        Task<CallResponse> CreateCall(string toNumber, string fromNumber, Nccos.Ncco ncco);
It can't be done as method cannot be overloaded by return type.The compiler will throw exception stating that method is already defined

2020-10-22 15:49 UTC, gagandeepp commented on Vonage/Voice/IVoiceClient.cs
> +        Task<CallResponse> CreateCall(string toNumber, string fromNumber, Nccos.Ncco ncco);
If you want I can create method with new name

2020-10-22 15:52 UTC, gagandeepp commented on Vonage/Voice/IVoiceClient.cs
> +using Nexmo.Api.Voice.Nccos;
Fixed

2020-10-22 15:53 UTC, gagandeepp commented on Vonage/Voice/VoiceClient.cs
> +        public const string CALLS_ENDPOINT_LATEST = "v2/calls";
Fixed

2020-10-22 15:53 UTC, gagandeepp commented on Vonage/Voice/VoiceClient.cs
> +using Nexmo.Api.Voice.Nccos;
Fixed

2020-10-22 15:53 UTC, gagandeepp commented on Vonage/Voice/IVoiceClient.cs
> +        Task<CallResponse> CreateCall(PhoneEndpoint toEndPoint, string fromNumber, Nccos.Ncco ncco);
Fixed

2020-10-22 15:53 UTC, gagandeepp commented on Vonage/Voice/VoiceClient.cs
> +
Fixed

2020-10-22 16:40 UTC, slorello89 requested changes
Couple more items - as for the async vs sync the pattern is to have the sync version of the method have the methods name and to have the async version have the same name with `Async` appended to the end. So in this case `CreateCallAsync`

2020-10-22 16:40 UTC, slorello89 commented on Vonage/Voice/IVoiceClient.cs
> +using Nexmo.Api.Voice.Nccos.Endpoints;
Wrong Namespace

2020-10-22 16:40 UTC, slorello89 commented on Vonage/Voice/IVoiceClient.cs
> +        Task<CallResponse> CreateCall(string toNumber, string fromNumber, Nccos.Ncco ncco);
You are correct a straight override won't work. The pattern is usually to have the sync version have the regular name and the async version to have the same name with `Async` appended to the end - so `CreateCallAsync`

2020-10-22 16:40 UTC, slorello89 commented on Vonage/Voice/VoiceClient.cs
> +using Nexmo.Api.Voice.Nccos.Endpoints;
Wrong namespace

2020-10-22 16:40 UTC, slorello89 commented on Vonage/Voice/VoiceClient.cs
> +        public const string CALLS_ENDPOINT_LATEST = "v1/calls";
this constant can be removed.

2020-10-22 16:40 UTC, slorello89 commented on Vonage/Voice/VoiceClient.cs
> -
let's keep this whitespace here.

2020-10-22 16:40 UTC, slorello89 commented on Vonage/Voice/VoiceClient.cs
> +        /// POST /v2/calls - create an outbound SIP or PSTN Call
`/v1/calls`

2020-10-22 16:40 UTC, slorello89 commented on Vonage/Voice/VoiceClient.cs
> +        /// POST /v2/calls - create an outbound SIP or PSTN Call
`/v1/calls`

2020-10-22 18:03 UTC, gagandeepp commented
Can you merge this ?

2020-10-22 18:27 UTC, slorello89 requested changes

2020-10-22 18:27 UTC, slorello89 commented on Vonage/Voice/VoiceClient.cs
> +            var command = new Voice.CallCommand
so we're not duplicating logic here it's best to route the `CreateCall` through the `CreateCallAsync`, all it will do is return `CreateCallAsync(toNumber,fromNumber,ncco).GetAwaiter().GetResult()`

That way we don't have to duplicate the logic and the error propagation will work as it would for any other sync method

2020-10-22 18:27 UTC, slorello89 commented on Vonage/Voice/VoiceClient.cs
> +            var command = new Voice.CallCommand
Same with this one running through the async method

2020-10-23 15:13 UTC, gagandeepp commented
@slorello89  Can you please give it a look?

2020-10-23 16:16 UTC, slorello89 commented
Hi @gagandeepp - I see you brought the other PRs branch into this one? those changes should be reverted - also see the comments I left yesterday

2020-10-27 04:52 UTC, gagandeepp commented
> Hi @gagandeepp - I see you brought the other PRs branch into this one? those changes should be reverted - also see the comments I left yesterday

The changes has been done ,please review

2020-10-27 20:31 UTC, slorello89 requested changes

2020-10-27 20:31 UTC, slorello89 commented on Vonage.Test.Unit/VoiceClientTests.cs
> +            var expectedRequesetContent = @"{""to"":[{""number"":""14155550100"",""dtmfAnswer"":""p*123#"",""type"":""phone""}],""from"":{""number"":""14155550100"",""dtmfAnswer"":""p*123#"",""type""
replace this string with `@"{""to"":[{""number"":""14155550100"",""type"":""phone""}],""from"":{""number"":""14155550100"",""type"":""phone""},""ncco"":[{""text"":""Hello World"",""action"":""talk""}]}"`

2020-10-27 20:31 UTC, slorello89 commented on Vonage.Test.Unit/VoiceClientTests.cs
> +            var expectedUri = "https://api.nexmo.com/v2/calls/";
replace this string with `$"{ApiUrl}/v1/calls/"`

2020-10-27 20:31 UTC, slorello89 commented on Vonage.Test.Unit/VoiceClientTests.cs
> +            var expectedRequesetContent = @"{""to"":[{""number"":""14155550100"",""dtmfAnswer"":""p*123#"",""type"":""phone""}],""from"":{""number"":""14155550100"",""dtmfAnswer"":""p*123#"",""type""
replace this string with `@"{""to"":[{""number"":""14155550100"",""type"":""phone""}],""from"":{""number"":""14155550100"",""type"":""phone""},""ncco"":[{""text"":""Hello World"",""action"":""talk""}]}"`

2020-10-27 20:31 UTC, slorello89 commented on Vonage.Test.Unit/VoiceClientTests.cs
> +            var expectedUri = "https://api.nexmo.com/v2/calls/";
replace this string with `$"{ApiUrl}/v1/calls/"`

2020-10-27 20:31 UTC, slorello89 commented on Vonage.Test.Unit/VoiceClientTests.cs
> +            var toEndpoint = new Nexmo.Api.Voice.Nccos.Endpoints.PhoneEndpoint() { Number = "14155550100" };
Remove the literal namespacing here - should just be `PhoneEndpoint`

2020-10-27 20:31 UTC, slorello89 commented on Vonage.Test.Unit/VoiceClientTests.cs
> +                toEndpoint.ToString(), "14155550100", new Voice.Nccos.Ncco(new Voice.Nccos.TalkAction { Text = "Hello World" }));
should not be using `toEndpoint` - not sending it to a string - that just puts the class name in as the to number

2020-10-27 20:31 UTC, slorello89 commented on Vonage/Voice/VoiceClient.cs
> +                    new Voice.Nccos.Endpoints.PhoneEndpoint
should not be creating a new endpoint here - just pass the endpoint gotten from the arguments into this.

2020-10-28 03:57 UTC, gagandeepp commented on Vonage.Test.Unit/VoiceClientTests.cs
> +                toEndpoint.ToString(), "14155550100", new Voice.Nccos.Ncco(new Voice.Nccos.TalkAction { Text = "Hello World" }));
Not clear from comment

2020-10-28 13:51 UTC, slorello89 commented on Vonage.Test.Unit/VoiceClientTests.cs
> +                toEndpoint.ToString(), "14155550100", new Voice.Nccos.Ncco(new Voice.Nccos.TalkAction { Text = "Hello World" }));
The way the CreateCallAsync is being used here - it's passing in a string rather than the endpoint itself.

2020-10-28 14:49 UTC, gagandeepp commented
@slorello89  Can you please review and accept the PR?

2020-10-28 16:01 UTC, slorello89 requested changes
Just 1 more thing.

2020-10-28 16:01 UTC, slorello89 commented on Vonage/Voice/VoiceClient.cs
> +        CallResponse IVoiceClient.CreateCall(Endpoint toEndPoint, string fromNumber, Ncco ncco)
Same for this one.

2020-10-29 04:37 UTC, gagandeepp commented
done,please review

2020-10-29 13:06 UTC, slorello89 approved these changes
Hi @gagandeepp, Thanks so much for bearing with all of my reviews! Just tested everything on my end and it looks great. Thank you so much for this contribution - it will be very helpful :). Happy Hacktoberfest 👻 🎃 👻 🎃 !!!

2020-10-29 13:06 UTC, merged