Enhancements to the ISmsClient
Vonage/vonage-dotnet-sdk pull request #239
Opened 2020-11-25 16:06 UTC by Cereal-Killa

In reference to #222 
Simplifies the way an sms can be sent.

2020-12-01 23:53 UTC, slorello89 requested changes
Looks great on my end - tested it out, makes much simpler thanks so much for this @Cereal-Killa. Just 2 ultra-minor items surrounding a namespace scoping.

2020-12-01 23:53 UTC, slorello89 commented on Vonage/Messaging/SmsClient.cs
> +            return SendAnSmsAsync(new Messaging.SendSmsRequest { From = from, To = to, Type = type, Text = text }, creds);
Can you chop the `Messaging` scoping out of this? It should already be in the namespace :)

2020-12-01 23:53 UTC, slorello89 commented on Vonage/Messaging/SmsClient.cs
> +            return SendAnSms(new Messaging.SendSmsRequest { From = from, To = to, Type = type, Text = text }, creds);
Same with this spot - just replace `Messaging.SendSmsRequest` with `SendSmsRequest`

2020-12-02 12:55 UTC, Cereal-Killa commented
> Looks great on my end - tested it out, makes much simpler thanks so much for this @Cereal-Killa. Just 2 ultra-minor items surrounding a namespace scoping.

Absolutely, I missed that. It's all set now.

2020-12-08 13:00 UTC, slorello89 approved these changes
Looks great @Cereal-Killa - will push this out in the next release

2021-01-12 20:38 UTC, merged