Meetings/rooms
Vonage/vonage-dotnet-sdk pull request #339
Opened 2023-01-26 09:07 UTC by Tr00d

2023-02-08 10:46 UTC, SMadani requested changes
Just a note on some of the types, otherwise LGTM it's been tested and proven to work.

2023-02-08 10:46 UTC, SMadani commented on Vonage/Meetings/UpdateRoom/UpdateRoomRequestBuilder.cs
> +    private Maybe<string> expiresAt;
Could be a date?

2023-02-08 10:46 UTC, SMadani commented on Vonage/Meetings/GetRoomsByTheme/GetRoomsByThemeRequest.cs
> +    public Maybe<string> StartId { get; internal init; }
startId and endId should be nullable integers.

2023-02-08 10:46 UTC, SMadani commented on Vonage/Meetings/CreateTheme/CreateThemeRequestBuilder.cs
> +    private Maybe<Uri> shortCompanyUrl = Maybe<Uri>.None;
shortCompanyUrl is actually a string. It's what gets appended to `meetings.vonage.com`

2023-02-08 10:46 UTC, SMadani commented on Vonage/Meetings/CreateRoom/CreateRoomRequestBuilder.cs
> +    private RoomApprovalLevel approvalLevel = RoomApprovalLevel.None;
Can this not be null by default? Same with other properties. Let the backend set these.

2023-02-08 10:46 UTC, SMadani commented on Vonage/Meetings/Common/Theme.cs
> +    public Uri ShortCompanyUrl { get; set; }
string

2023-02-08 10:46 UTC, SMadani commented on Vonage/Meetings/UpdateThemeLogo/UploadLogoRequest.cs
> +        content.Add(new StringContent(this.Filepath), "file");
Should be binary content, not string?

2023-02-08 14:18 UTC, Tr00d commented on Vonage/Meetings/UpdateRoom/UpdateRoomRequestBuilder.cs
> +    private Maybe<string> expiresAt;
Indeed, I missed this one. It was already a DateTime on CreateRoom...

2023-02-08 14:27 UTC, Tr00d commented on Vonage/Meetings/CreateTheme/CreateThemeRequestBuilder.cs
> +    private Maybe<Uri> shortCompanyUrl = Maybe<Uri>.None;
A 'Uri' can be relative, it's not necessarily absolute. I just don't verify this one, I probably should.

2023-02-08 14:37 UTC, Tr00d commented on Vonage/Meetings/UpdateThemeLogo/UploadLogoRequest.cs
> +        content.Add(new StringContent(this.Filepath), "file");
`--form 'Content-Type="image/png"' \
--form 'key="auto-expiring-temp/logos/white/a2ef0569-7d2c-4297-b0dd-1af6d8b61be6"' \`
They use string content in the documentation. I received a 204 this way, so I assume it's working.

2023-02-08 14:40 UTC, SMadani commented on Vonage/Meetings/CreateTheme/CreateThemeRequestBuilder.cs
> +    private Maybe<Uri> shortCompanyUrl = Maybe<Uri>.None;
https://vonage.slack.com/archives/C02LM9QH6J0/p1675191424768749

2023-02-08 14:42 UTC, SMadani commented on Vonage/Meetings/CreateRoom/CreateRoomRequestBuilder.cs
> +    private RoomApprovalLevel approvalLevel = RoomApprovalLevel.None;
Null means unspecified (the default). NONE means no approval is needed.

2023-02-08 14:45 UTC, SMadani commented on Vonage/Meetings/UpdateThemeLogo/UploadLogoRequest.cs
> +        content.Add(new StringContent(this.Filepath), "file");
I think you're supposed to add the file as part of the request, otherwise you're just sending the path to a file on your local machine. Hence the `@` in the cURL request for the `file` parameter. Could be wrong though. Also I think you'd get a 204 regardless, it's the finalization that would fail.

2023-02-09 10:39 UTC, SMadani approved these changes

2023-02-09 10:50 UTC, merged