Sip/devx 6866
Vonage/vonage-dotnet-sdk pull request #355
Opened 2023-02-14 13:15 UTC by Tr00d

2023-02-15 10:20 UTC, SMadani requested changes
Mostly OK, just a couple of minor things.

2023-02-15 10:20 UTC, SMadani commented on Vonage.Server/Video/Sip/InitiateCall/InitiateCallResponse.cs
> +    public string ConnectionId { get; set; }
According to [this](https://tokbox.com/developer/rest/#sip_call) it seems all of the IDs can be a Guid.

2023-02-15 10:20 UTC, SMadani commented on Vonage.Server/Video/Sip/InitiateCall/SipElementBuilder.cs
> +        this.customHeaderKey = new SipElement.SipHeader(value);
I think this should be a Map<String, String>, to allow for multiple header key-value pairs. I could be wrong though.

2023-02-15 10:20 UTC, SMadani commented on Vonage.Server/Video/Sip/InitiateCall/SipElement.cs
> +        public SipAuthentication(string password, string username)
It's more intuitive to provide the username before the password.

2023-02-16 04:50 UTC, Tr00d commented on Vonage.Server/Video/Sip/InitiateCall/InitiateCallResponse.cs
> +    public string ConnectionId { get; set; }
Hm okay, our API specs didn't mention UUID, and I couldn't test by myself. So, I picked the safe route with a string. I'll change it

2023-02-16 04:51 UTC, Tr00d commented on Vonage.Server/Video/Sip/InitiateCall/SipElementBuilder.cs
> +        this.customHeaderKey = new SipElement.SipHeader(value);
I thought the same, and it would make sense. But in our spec, Headers is defined as an object, not an array. Hard to tell without actually testing. I don't know what to do with this one.

2023-02-16 04:58 UTC, Tr00d commented on Vonage.Server/Video/Sip/InitiateCall/SipElement.cs
> +        public SipAuthentication(string password, string username)
Indeed, I didn't pay attention. It should even have been a record in the first place.

2023-02-16 09:33 UTC, SMadani commented on Vonage.Server/Video/Sip/InitiateCall/SipElementBuilder.cs
> +        this.customHeaderKey = new SipElement.SipHeader(value);
Object just means it's a Map

2023-02-17 07:52 UTC, Tr00d commented on Vonage.Server/Video/Sip/InitiateCall/SipElementBuilder.cs
> +        this.customHeaderKey = new SipElement.SipHeader(value);
Okay, it's done

2023-02-17 10:13 UTC, SMadani approved these changes

2023-02-17 10:50 UTC, merged