[Video] DEVX-6861 Broadcasts
Vonage/vonage-dotnet-sdk pull request #356
Opened 2023-02-21 14:25 UTC by Tr00d

2023-02-23 14:38 UTC, SMadani requested changes
Some inaccuracies but otherwise it's fine :)

2023-02-23 14:38 UTC, SMadani commented on Vonage.Server/Video/Broadcast/AddStreamToBroadcast/AddStreamToBroadcastRequest.cs
> +    public string GetEndpointPath() => $"/v2/project/{this.ApplicationId}/broadcast/{this.BroadcastId}";
Should end in `/streams`

2023-02-23 14:38 UTC, SMadani commented on Vonage.Server/Video/Broadcast/BroadcastClient.cs
> +public class BroadcastClient
Missing `ListBroadcasts`

2023-02-23 14:38 UTC, SMadani commented on Vonage.Server/Video/Broadcast/Common/Broadcast.cs
> +    public long MaxDuration { get; set; }
Should be an int?

2023-02-23 14:38 UTC, SMadani commented on Vonage.Server/Video/Broadcast/Common/Broadcast.cs
> +    public LiveStream[] Streams { get; set; }
See previous comment (spec is wrong)

2023-02-23 14:38 UTC, SMadani commented on Vonage.Server/Video/Broadcast/Common/Broadcast.cs
> +    public record HlsSettings(bool Dvr, bool LowLatency);
Validation needed (can't both be true)

2023-02-23 14:38 UTC, SMadani commented on Vonage.Server/Video/Broadcast/RemoveStreamFromBroadcast/RemoveStreamFromBroadcastRequest.cs
> +    public string GetEndpointPath() => $"/v2/project/{this.ApplicationId}/broadcast/{this.BroadcastId}";
Add `/streams` to the URL

2023-02-23 14:38 UTC, SMadani commented on Vonage.Server/Video/Broadcast/StopBroadcast/StopBroadcastRequest.cs
> +    public string GetEndpointPath() => $"/v2/project/{this.ApplicationId}/broadcast/{this.BroadcastId}";
Need to add `/stop` to the URL

2023-02-23 15:23 UTC, Tr00d commented on Vonage.Server.Test/Video/Broadcast/GetBroadcasts/Data/ShouldDeserialize200-response.json
> +      "streams": [
The specs contain a 'streams' property. It's just not on the JSON example.
https://tokbox.com/developer/rest/#get_info_broadcast

2023-02-23 15:24 UTC, Tr00d commented on Vonage.Server.Test/Video/Broadcast/GetBroadcasts/Data/ShouldDeserialize200-response.json
> +        "hls": {
It doesn't matter here. This is part of a test to verify I'm able to deserialize the API's response. 
The response itself is just a DTO without any logic

2023-02-23 15:28 UTC, Tr00d commented on Vonage.Server.Test/Video/Broadcast/GetBroadcast/Data/ShouldDeserialize200-response.json
> +  "streams": [
The specs contain a 'streams' property. It's just not on the JSON example.
https://tokbox.com/developer/rest/#get_info_broadcast

2023-02-23 15:30 UTC, Tr00d commented on Vonage.Server.Test/Video/Broadcast/StartBroadcast/Data/ShouldSerializeWithDefaultValues-request.json
> +  "maxBitrate": 1000,
I didn't see any validation on maxBitrate. Indeed, it's very low, but it's a serialization test and an int after all.

2023-02-23 15:37 UTC, Tr00d commented on Vonage.Server/Video/Broadcast/BroadcastClient.cs
> +public class BroadcastClient
It's there, just under GetBroadcasts (plural)

2023-02-23 15:53 UTC, Tr00d commented on Vonage.Server.Test/Video/Broadcast/RemoveStreamFromBroadcast/RemoveStreamFromBroadcastRequestBuilderTest.cs
> +                .BeFailure(ResultFailure.FromErrorMessage("BroadcastId cannot be empty."));
No, broadcastId has been set with Guid.Empty here

2023-02-23 15:58 UTC, SMadani commented on Vonage.Server/Video/Broadcast/BroadcastClient.cs
> +public class BroadcastClient
Ah ok. It's just that we usually call endpoints that return a list `ListX` (see https://github.com/Nexmo/server-sdk-specification/blob/main/SPECIFICATION.md#verbs) but it might be different in the .NET SDK, so whatever's consistent with existing implementation of other APIs :)

2023-02-23 22:15 UTC, SMadani commented on Vonage.Server.Test/Video/Broadcast/GetBroadcast/Data/ShouldDeserialize200-response.json
> +  "streams": [
My bad 😅

2023-02-24 10:14 UTC, SMadani approved these changes

2023-02-24 10:15 UTC, merged