feat: proactive connect items
Vonage/vonage-dotnet-sdk pull request #399
Opened 2023-04-25 08:54 UTC by Tr00d

2023-04-26 15:06 UTC, manchuck commented on Vonage.Test.Unit/ProactiveConnect/Items/CreateItem/Data/ShouldSerialize-request.json
> +}
What happens if there is a very complex object?

```json
{
    "data": {
        "fizz": {
            "foo": "bar"
        },
        "baz": 2,
        "Bat": "qux",
        "more_items": [
            1,
            2,
            "three",
            true,
            {"foo": "bar"}
        ]
    }
}
```

2023-04-26 15:15 UTC, manchuck requested changes
Just need to add the `order` parameter

2023-04-27 05:52 UTC, Tr00d commented on Vonage.Test.Unit/ProactiveConnect/Items/CreateItem/Data/ShouldSerialize-request.json
> +}
It should work the same, given the type is `object`. Upon deserialization, the property may hold a `JsonElement`. Of course, C# does not like when the type cannot be determined...
Now, in a potential scenario, I assume that if the customer can put data in with a type (Hello C#), the customer should be able to pull the data out using the same type.
I'm gonna highlight that with another test, just in case.

2023-04-27 06:01 UTC, Tr00d commented on Vonage.Test.Unit/ProactiveConnect/Items/CreateItem/Data/ShouldSerialize-request.json
> +}
Indeed, it works. I was sceptical about using anonymous types.
Deserialization works too, but manipulating `JsonElement` is painful. I'd recommend customers to use typed instances to avoid too much hustle (especially since it's small and easy with record types).

```csharp
 [Fact]
        public void ShouldSerializeComplexObject() =>
            CreateItemRequest
                .Build()
                .WithListId(Guid.NewGuid())
                .WithCustomData(new KeyValuePair<string, object>("fizz", new {Foo = "bar"}))
                .WithCustomData(new KeyValuePair<string, object>("baz", 2))
                .WithCustomData(new KeyValuePair<string, object>("Bat", "qux"))
                .WithCustomData(new KeyValuePair<string, object>("more_items", new object[]
                {
                    1,
                    2,
                    "three",
                    true,
                    new {Foo = "bar"},
                }))
                .Create()
                .GetStringContent()
                .Should()
                .BeSuccess(this.helper.GetRequestJson());
```

2023-04-27 06:02 UTC, Tr00d commented on Vonage/ProactiveConnect/Items/GetItems/GetItemsRequest.cs
> +}
Will do.

2023-04-28 13:14 UTC, merged